name: "Ci/CD - Terse Theme"

on:
  push:
    branches:
      - main

jobs:
  deploy-theme:
    runs-on: ubuntu-latest
    steps:
      - name: "Step | Checkout Repo"
        uses: actions/checkout@v3
        continue-on-error: false
      - name: "Step | Theme Deploy"
        uses: "TryGhost/action-deploy-theme@1"
        with:
          api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
          theme-zip: "terse.zip"
          activate: true
          continue-on-error: false
